---
title: "Map animations using gganimate"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Animated maps

```{r data}
library(gganimate)
library(ggplot2)
library(dplyr)

map_coordinates <- readRDS("citiesinparl/map_coordinates.rds")
not_city <- readRDS("citiesinparl/not_city.rds")

recession <- map_coordinates %>% 
  filter(period == "1986-1995")

crisis <- map_coordinates %>% 
  filter(period == "2004-2013")

global_limits = c(0, max(map_coordinates$mention_count, na.rm=TRUE))
global_limits_per_capita = c(0, max(map_coordinates$per_capita, na.rm=TRUE))



theme_set(
  theme_minimal(base_family = "Arial") +
    theme(legend.position= "none",
          axis.text = element_blank(),
          axis.title = element_blank(),
          panel.grid = element_blank()
    )
)

```

## 90s Recession

### Absolute

```{r recession_abs}
animated1 <- ggplot() +
  geom_sf(data = not_city, col = alpha("white", 1/3), fill = "grey") +
  geom_sf(data = recession, aes(fill = mention_count , geometry = geom), colour = alpha("white", 1/3)) +
  viridis::scale_fill_viridis(limits = global_limits) +
  labs(title = "Cities mentioned in plenary sessions of\nFinnish parliament 1986-1995",
       subtitle = "Year: {closest_state}", fill = "No. mentions") +
  theme(legend.position = "right") +
  transition_states(year, 10, 3)

animate(animated1)
```

### Per capita

```{r recession_per_capita}
animated2 <- ggplot() +
  geom_sf(data = not_city, col = alpha("white", 1/3), fill = "grey") +
  geom_sf(data = recession, aes(fill = per_capita , geometry = geom), colour = alpha("white", 1/3)) +
  viridis::scale_fill_viridis(limits = global_limits_per_capita) +
  labs(title = "Cities mentioned in plenary sessions of\nFinnish parliament 1986-1995",
       subtitle = "Year: {closest_state}", fill = "No. mentions\nper capita",
       caption = "Municipal population data: Statistics Finland (2021)") +
  theme(legend.position = "right") +
  transition_states(year, 10, 3)

animate(animated2)
```



## Financial Crisis

### Absolute

```{r recession_abs}
animated3 <- ggplot() +
  geom_sf(data = not_city, col = alpha("white", 1/3), fill = "grey") +
  geom_sf(data = crisis, aes(fill = mention_count , geometry = geom), colour = alpha("white", 1/3)) +
  viridis::scale_fill_viridis(limits = global_limits) +
  labs(title = "Cities mentioned in plenary sessions of\nFinnish parliament 2004-2013",
       subtitle = "Year: {closest_state}", fill = "No. mentions") +
  theme(legend.position = "right") +
  transition_states(year, 10, 3)

animate(animated3)
```

### Per capita

```{r recession_per_capita}
animated4 <- ggplot() +
  geom_sf(data = not_city, col = alpha("white", 1/3), fill = "grey") +
  geom_sf(data = crisis, aes(fill = per_capita , geometry = geom), colour = alpha("white", 1/3)) +
  viridis::scale_fill_viridis(global_limits_per_capita) +
  labs(title = "Cities mentioned in plenary sessions of\nFinnish parliament 2004-2013",
       subtitle = "Year: {closest_state}", fill = "No. mentions\nper capita",
       caption = "Municipal population data: Statistics Finland (2021)") +
  theme(legend.position = "right") +
  transition_states(year, 10, 3)

animate(animated4)
```


